---
- hosts: ubuntu
  gather_facts: no
  become: true
  become_user: root
  become_method: sudo

  tasks:

  - name: Update repositories cache and install docker package
    become: true
    apt:
      name: docker.io
      update_cache: yes

  - name: Upgrade all packages to the latest version
    become: true
    apt:
      name: "*"
      state: latest
