---
- hosts: controller
  become: true
  gather_facts: no
  become_user: root
  become_method: sudo

  tasks:

  - name: Transfer and exctact Avi software
    unarchive:
      src: "{{ AviBinFile }}"
      dest: ./

#  - name: copy bin file from the ansible host to the controller host
#    become: true
#    copy:
#      src: /home/avi/bin/avi/{{ bin_filename }}
#      dest: /tmp/{{ bin_filename }}

#  - name: Unzip bin file 
#    become: true
#    shell: |
#      cd /home/avi
#      tar -xvf {{ bin_filename }}
#    register: unzipvalue
#
#  - name: show output
#    debug:
#      var: unzipvalue.stdout

  - name: install avi controller
    become: true
    shell: |
      ./avi_baremetal_setup.py -c -cc "{{ AviControllerCpu }}" -cm "{{ AviControllerMem }}" -i "{{ AviControllerIp }}"

    register: shellvalue


  - name: show output
    debug:
      var: shellvalue.stdout


#
# EXAMPLE: ansible-playbook -i hosts --extra-vars="bin_filename=docker_install-18.1.3-9144.tar.gz ip_controller=192.168.17.151" 03-install-controller.yml
#
